channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.3
  - h5py=2.7.1
  - hdf5=1.8.18
  - ipython=6.2.1
  - jupyter=1.0.0
  - jupyterlab=0.34.9
  - keras=2.1.5
  - matplotlib=3.1
  - notebook=5.2.0
  - numpy=1.14.6
  - pandas=0.20.3
  - pillow=5.4.1
  - pip=9.0.1
  - pytest=3.2.3
  - pytest-arraydiff
  - pytz=2017.2
  - pyyaml=3.12
  - scikit-image=0.14.2
  - scikit-learn=0.20.3
  - seaborn=0.9.0
  - sympy=1.1.1
  - tensorflow=1.5.0=py36_0
  - pytables=3.4.2=py36hc5f0ea4_2
  - scipy=1.0.0
  - sqlite=3.23.1
